# Generated by Django 4.1.5 on 2023-01-30 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
