# Generated by Django 4.1.5 on 2023-01-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0002_course_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
