# Generated by Django 4.1.5 on 2023-01-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attatchment',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='attatchment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='Topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='Course',
        ),
        migrations.AddField(
            model_name='lecture',
            name='Name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='attatchments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.attatchment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='attachments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.attatchment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent'),
            preserve_default=False,
        ),
    ]
