# Generated by Django 4.1.5 on 2023-01-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursecontent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='Name',
        ),
    ]
