# Generated by Django 4.1.5 on 2023-02-01 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_topic_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='Name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_added',
        ),
        migrations.AddField(
            model_name='course',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
