# Generated by Django 4.1.5 on 2023-02-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewp', '0004_initial'),
        ('courses', '0007_alter_topic_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Banner',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ewp.university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attatchment',
            name='embed_type',
            field=models.CharField(choices=[('GD', 'gdrive'), ('YT', 'youtube'), ('LK', 'link'), ('IM', 'image')], default='LK', max_length=2),
        ),
        migrations.AlterField(
            model_name='attatchment',
            name='link_id',
            field=models.CharField(max_length=255),
        ),
    ]
