# Generated by Django 4.1.5 on 2023-02-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_description_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creator',
            new_name='author',
        ),
    ]
