# Generated by Django 4.1.5 on 2023-02-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_content_alter_course_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='attachments',
        ),
        migrations.AddField(
            model_name='topic',
            name='Lectures',
            field=models.ManyToManyField(to='courses.lecture'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='attatchments',
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
        migrations.AddField(
            model_name='course',
            name='Content',
            field=models.ManyToManyField(to='courses.topic'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='attatchments',
            field=models.ManyToManyField(to='courses.attatchment'),
        ),
    ]
