# Generated by Django 4.1.5 on 2023-02-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_topic_attachments_topic_lectures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Content',
            field=models.ManyToManyField(blank=True, to='courses.topic'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='attatchments',
            field=models.ManyToManyField(blank=True, to='courses.attatchment'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Lectures',
            field=models.ManyToManyField(blank=True, to='courses.lecture'),
        ),
    ]
